/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/eioannidis/karamel/_build/default/src/Karamel.exe -skip-compilation -skip-makefiles -skip-linking -bundle CircularBufferWrapper=CircularBufferWrapper,Pulse.Lib.CircularBuffer,Pulse.Lib.CircularBuffer.Spec,Pulse.Lib.CircularBuffer.GapTrack,Pulse.Lib.CircularBuffer.Pow2,Pulse.Lib.CircularBuffer.Modular -no-prefix CircularBufferWrapper -warn-error -15-2-4-7-3-1-5 -tmpdir /tmp/cb_nofsti/c_out /tmp/cb_nofsti/CircularBufferWrapper.krml /tmp/cb_nofsti/Pulse_Lib_CircularBuffer.krml /tmp/cb_nofsti/Pulse_Lib_CircularBuffer_Spec.krml /tmp/cb_nofsti/Pulse_Lib_CircularBuffer_GapTrack.krml /tmp/cb_nofsti/Pulse_Lib_CircularBuffer_Pow2.krml /tmp/cb_nofsti/Pulse_Lib_CircularBuffer_Modular.krml
  F* version: <unknown>
  KaRaMeL version: 1d8e0b74
 */

#ifndef CircularBufferWrapper_H
#define CircularBufferWrapper_H

#include "krmllib.h"

typedef struct Pulse_Lib_CircularBuffer_cb_internal_s
{
  uint8_t *buf;
  size_t rs;
  size_t al;
  size_t pl;
  size_t vl;
}
Pulse_Lib_CircularBuffer_cb_internal;

typedef uint8_t byte;

Pulse_Lib_CircularBuffer_cb_internal *create0(size_t alloc_len, size_t virt_len);

size_t read_length0(Pulse_Lib_CircularBuffer_cb_internal *cb);

void drain0(Pulse_Lib_CircularBuffer_cb_internal *cb, size_t n);

void resize0(Pulse_Lib_CircularBuffer_cb_internal *cb, size_t new_al);

void free0(Pulse_Lib_CircularBuffer_cb_internal *cb);

size_t get_alloc_length0(Pulse_Lib_CircularBuffer_cb_internal *cb);

bool write_buffer0(Pulse_Lib_CircularBuffer_cb_internal *cb, uint8_t *src, size_t write_len);

void read_buffer0(Pulse_Lib_CircularBuffer_cb_internal *cb, uint8_t *dst, size_t read_len);


#define CircularBufferWrapper_H_DEFINED
#endif /* CircularBufferWrapper_H */
