name: CLOG

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

permissions: read-all

jobs:
  validate:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Validate
    runs-on: windows-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7
      with:
        dotnet-version: 10.0.x
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Prepare Machine
      run: scripts/prepare-machine.ps1
      shell: pwsh
    - name: Run CLOG Update
      run: scripts/update-sidecar.ps1
      shell: pwsh
    - name: Check for Changes
      run: |
        git add .
        git --no-pager diff --exit-code HEAD
