name: CLOG

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

permissions: read-all

jobs:
  validate:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Validate
    runs-on: windows-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
      with:
        dotnet-version: 10.0.x
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Prepare Machine
      run: scripts/prepare-machine.ps1
      shell: pwsh
    - name: Run CLOG Update
      run: scripts/update-sidecar.ps1
      shell: pwsh
    - name: Check for Changes
      run: |
        git add .
        git --no-pager diff --exit-code HEAD
