name: BVT

on:
  workflow_dispatch:
    inputs:
      ref:
        required: false
        default: ''
        type: string
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

jobs:
  test:
    name: Test
    runs-on:
    - self-hosted
    - 1ES.Pool=1es-msquic-pool
    steps:
    - name: Print OS information
      run: Get-ComputerInfo | Select-Object -Property WindowsBuildLabEx
      shell: pwsh
    - name: Print Powershell Version
      run: $PSVersionTable
      shell: pwsh
    - name: Double check and make sure
      run: pwsh --version
      shell: pwsh
